"""Populating the Database

Revision ID: 2bb3b7a007e2
Revises: 95fa9ef0abf1
Create Date: 2023-09-08 14:19:07.187988

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2bb3b7a007e2'
down_revision = '95fa9ef0abf1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
